import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/layout/AppSidebar";
import Header from "@/components/layout/Header";
import "./globals.css";
import { PromptProvider } from "./context/PromptContext";
import { HeaderProvider } from "@/app/context/HeaderContext";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <PromptProvider>
            <SidebarProvider>
              <AppSidebar />
              <HeaderProvider>
                <div className="relative flex-1 z-10">
                  <Header />
                  {children}
                </div>
                <Toaster />
              </HeaderProvider>
            </SidebarProvider>
          </PromptProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
